### PR TITLE
Fixes for native binaries build system

### PR DESCRIPTION
**Pull request by aelmahmoudy**

### CODE REVIEW

**Comment by n8fr8** [comment]
Thanks for this PR! Will review and let you know if I have any questions.

**Comment by aelmahmoudy** [comment]
Thanks.

Could you explain the vercode numbering scheme that is used in Orbot now ? The reason is that we build two versions of Orbot, one for pre android-16 compile without PIE, and the other one compile with PIE). Hence we give the version compile without PIE a lesser vercode than the one compiled with PIE.

**Comment by n8fr8** [comment]
When you say "we build", can you tell me a little more about that? Are you redistributing Orbot as part of another app, or under another brand? Just curious and excited to hear about your work.

Otherwise, yes, I hadn't considered your use of the vercode for this purpose. I will take a look at VLC.

**Comment by aelmahmoudy** [comment]
Oh, sorry, I mean "we" on F-Droid repository

**Comment by n8fr8** [comment]
Ah, thanks! The "royal we" as they say!

**Comment by aelmahmoudy** [comment]
Erm, actually I meant F-Droid team, not just myself.

By the way, how could I build meek-client & obfs4proxy ? Is there some sort of cross-platform "go" compiler that I should use ?

**Comment by n8fr8** [comment]
Yes, all the Go build information for PT's is here: https://github.com/guardianproject/pluto

I haven't integrated into our Makefile yet but I am planning on it as some point.

**Pull request merged**
