### PR TITLE
fix for bug https://github.com/n8fr8/orbot/issues/63

### PR DESCRIPTION
**Pull request by arrase**
fix for: https://github.com/n8fr8/orbot/issues/63

### CODE REVIEW

**Comment by arrase** [comment]
ouch! .... there more problems to solve ....

    private void updateStatus(String torServiceMsg) {
    	if (torStatus == null)
    		return; //UI not init'd yet

**Comment by arrase** [comment]
i think that solves the issue without big changes

**Comment by arrase** [comment]
@n8fr8 consider this fix

**Comment by n8fr8** [comment]
This fix was merged

**Comment by n8fr8** [comment]
Thanks!

**Pull request closed without merging**
